### ISSUE TITLE
try_init shouldn't set the LevelFilter if there was already a logger

### ISSUE THREAD

**Issue by bnjbvr** [sebasmagri/env_logger#116]
edit: sorry, pressed Enter too fast.

I've had an issue where our library (Spidermonkey) has two ways to initialize the global logger:
- one in a standalone environment
- one embedded in a bigger program (Firefox)

In the program case, the program will first initialize its logger with a specific LevelFilter; then the code runs into our initialization path that runs `env_logger::try_init()` which fails since a logger has already been set. Unfortunately, this also resets the LevelFilter. There's an easy workaround on our side, but I thought in general you wouldn't want to implicitly override the LevelFilter if there was already a logger set. Thoughts?

**Comment by KodrAus** [comment]
Ah thanks for the report @bnjbvr!

Yeh that behaviour is definitely surprising. If there's already a global logger we shouldn't clobber the max level. We should be able to just check whether we successfully set the logger before attempting to set the level filter. It's slightly racy, but I don't think it's really any racier than what we do now where we set the level filter then attempt to set the logger.
