### ISSUE TITLE
Please add a changelog that links to the release notes

### ISSUE THREAD

**Issue by shepmaster** [sebasmagri/env_logger#119]
Over time, I've grown accustomed to a CHANGELOG file. It's cool [if you want to use GitHub releases](https://github.com/sebasmagri/env_logger/releases), but it's not immediately obvious that this is where the notes are. A plain text file with a link would be sufficient.

**Comment by KodrAus** [comment]
Hi @shepmaster, that sounds good to me. PRs accepted ;)
