### ISSUE TITLE
LogLevelFilter - overhead effect

### ISSUE THREAD

**Issue by yoni386** [sebasmagri/env_logger#121]
Hello, 

log = "0.3.8"
env_logger = "0.4.3"

Is it free to use macro debug! or trace! when LogLevelFilter is set to Info? LogLevelFilter::Info 
Is There  extra overhead when using LogLevelFilter::Info or LogLevelFilter::Debug and using trace!(very_large_stream)? is it not called or is redirected to /dev/null? how it done? is it in runtime or at compile time? 
`
 let mut builder = LogBuilder::new();

    if matches.is_present("debug") {
        let format = |record: &LogRecord| {
            format!(
                "{} [{}] {}:{} {:?} - {}",
                Local::now().format("%d-%m-%Y %H:%M:%S"),
                record.level(),
                record.location().file(),
                record.location().line(),
                thread::current().id(),
                record.args()
            )
        };

        if matches.is_present("trace") {
            builder.format(format).filter(None, LogLevelFilter::Trace);
        } else {
            builder.format(format).filter(None, LogLevelFilter::Debug);
        }

    } else {
        let format = |record: &LogRecord| {
            format!(
                "{} [{}] - {}",
                Local::now().format("%d-%m-%Y %H:%M:%S"),
                record.level(),
                record.args()
            )
        };

        builder.format(format).filter(None, LogLevelFilter::Info);
    }

    builder.init().unwrap();
`

**Comment by KodrAus** [comment]
Hi @yoni386 

Checking whether a given record should be logged is handled by the `log` crate, which does an atomic load and compare to see whether we should proceed. If not, then nothing else happens, there's no logging to `/dev/null`, the log record is simply not produced. So it's not totally free, but is very cheap.

**Comment by KodrAus** [comment]
I'll go ahead and close this one, but if you've got any more questions please feel free to re-open or log new issues!
