### ISSUE TITLE
timestamps with milliseconds

### ISSUE THREAD

**Issue by nlevitt** [sebasmagri/env_logger#122]
I read through https://github.com/sebasmagri/env_logger/issues/87 and I can't help but (humbly) second-guess (no pun intended) the decision. In my opinion, second-level precision is too coarse, and nanosecond-level is too fine, and milliseconds are the happy medium. And I would argue that it doesn't even need to be configurable. I'd propose that if `default_format_timestamp` logged millisecond-level timestamps, that would be good enough for almost everybody. I realize `humantime` doesn't support milliseconds, so I guess this would mean going back to chronos, unless we can convince humantime to add that...

**Comment by KodrAus** [comment]
Thanks for the feedback @nlevitt!

Finding a good default precision is definitely tricky. If `humantime` did support milliseconds then I would be in favour of popping millis in the default timestamp format, but don't personally think it's too coarse as-is, so wouldn't move back to `chrono` just for millis.

**Comment by nlevitt** [comment]
👍 ok thanks!

**Comment by tailhook** [comment]
Just released humantime v1.3.0 that has millis formatting. By the way, my favourite log format also includes milliseconds :)
