### ISSUE TITLE
Any way to log to a file?

### ISSUE THREAD

**Issue by bbigras** [sebasmagri/env_logger#125]
Any way to log to a file?

If not could it be a feature request?

**Comment by bbigras** [comment]
> You should be able to pipe the output stream from your application into a file.

Yes this is enough when running in docker, systemd or as a Windows service with NSSM. However I don't know how to pipe the output stream on Windows for a non-console application.

Do you know by chance if there's a simple way? With a Windows shortcut maybe. I would prefer not having to use a wrapper program.

**Comment by KodrAus** [comment]
It's been a little while so I'll go ahead and close this one now as something we won't be supporting in a first-class feature in `env_logger` itsef. If you've got any other questions though please feel free to open new issues!

**Comment by osa1** [comment]
Just came here to ask for this and found this issue -- I think it'd be good to mention that logging to a file is out of scope for this library as I think this'd be a common request from users.

**Comment by vext01** [comment]
I know it's been deemed out of scope, but thought I'd share a scenario where logging to file is necessary, and where I would have liked to have used envlogger.

I have a scenario where I have a [langtester](https://docs.rs/lang_tester/latest/lang_tester/) test suite that checks stdout/stderr of test binaries.

During debugging I need to be able to do "print debugging", but printing to either stdout/stderr will make tests fail. The only solution is to log to a file.

**Comment by vdominguez1993** [comment]
> I know it's been deemed out of scope, but thought I'd share a scenario where logging to file is necessary, and where I would have liked to have used envlogger.
> 
> I have a scenario where I have a [langtester](https://docs.rs/lang_tester/latest/lang_tester/) test suite that checks stdout/stderr of test binaries.
> 
> During debugging I need to be able to do "print debugging", but printing to either stdout/stderr will make tests fail. The only solution is to log to a file.

Configuring the target as pipe you can pass your file.
Let me share a working example that I'm using:
`let target = Box::new(File::create("/tmp/test.txt").expect("Can't create file"));

    Builder::new()
        .format(|buf, record| {
            writeln!(
                buf,
                "{}:{} {} [{}] - {}",
                record.file().unwrap_or("unknown"),
                record.line().unwrap_or(0),
                Local::now().format("%Y-%m-%dT%H:%M:%S%.3f"),
                record.level(),
                record.args()
            )
        })
        .target(env_logger::Target::Pipe(target))
        .filter(None, LevelFilter::Info)
        .init();`

If you need a more complex logger you can pass your own struct implementing std::io::Write.

**Comment by calmofthestorm** [comment]
Note that you may need to update to 0.9.3+ to make use of the above solution due to #208.

**Comment by sweihub** [comment]
Thanks, working example
```rust
use chrono::Local;
use log::*;
use std::fs::File;
use std::io::Write;

fn main() {
    let target = Box::new(File::create("log.txt").expect("Can't create file"));

    env_logger::Builder::new()
        .target(env_logger::Target::Pipe(target))
        .filter(None, LevelFilter::Debug)
        .format(|buf, record| {
            writeln!(
                buf,
                "[{} {} {}:{}] {}",
                Local::now().format("%Y-%m-%d %H:%M:%S%.3f"),
                record.level(),
                record.file().unwrap_or("unknown"),
                record.line().unwrap_or(0),
                record.args()
            )
        })
        .init();

    debug!("debug line");
    info!("Hello world");
    info!("Hello world");
    info!("Hello world");
    info!("Hello world");
}

```

**Comment by sweihub** [comment]
Even simpler out-of-the-box async crate: [`log2`](https://crates.io/crates/log2)

```rust
use log2::*;

fn main() {
    let _log2 = log2::open("log.txt").start();

    trace!("send order request to server");
    debug!("receive order response");
    info!("order was executed");
    warn!("network speed is slow");
    error!("network connection as broken");
}
```

Outpu files
```
log.txt
log.1.txt
log.2.txt
log.3.txt
log.4.txt
log.5.txt
log.6.txt
log.7.txt
log.8.txt
log.9.txt
```

**Comment by mozboz** [comment]
> I know it's been deemed out of scope, but thought I'd share a scenario where logging to file is necessary, and where I would have liked to have used envlogger.
> 
> I have a scenario where I have a [langtester](https://docs.rs/lang_tester/latest/lang_tester/) test suite that checks stdout/stderr of test binaries.
> 
> During debugging I need to be able to do "print debugging", but printing to either stdout/stderr will make tests fail. The only solution is to log to a file.

Another example is TUI's where logging output will interfere with the UI
