### ISSUE TITLE
Add new separate filter_module and filter_level to Builder

### ISSUE THREAD

**Issue by sebasmagri** [sebasmagri/env_logger#13]

**Comment by KodrAus** [comment]
I think let's do this. The idea is we add two new methods to the `fmt::Builder` and root `Builder` types:

```rust
fn filter_module(&mut self, module: &str, level: LevelFilter) -> &mut Self {
    self.filter(Some(module), level)
}

fn filter_level(&mut self, level: LevelFilter) -> &mut Self {
    self.filter(None, level)
}
```

I think it's worthwhile because `filter(None, level)` actually means _apply to logs from all modules_. That seems a bit odd, since we're passing a value of `None` to the module.
