### ISSUE TITLE
Debug level is unreadable in light terminal themes

### ISSUE THREAD

**Issue by r-darwish** [sebasmagri/env_logger#138]
Since Debug level is set to white, it cannot be read in light terminal themes.

https://github.com/sebasmagri/env_logger/blob/8fa62401ceec3a7571565fb3437a7cf4b906f9ee/src/fmt/writer/termcolor/extern_impl.rs#L56

![image](https://user-images.githubusercontent.com/1383193/62420342-49727480-b699-11e9-8e40-1805fb023aba.png)

**Comment by KodrAus** [comment]
Thanks for the report @r-darwish!

Would you like to submit a PR that uses a colour that's more suitable for both light and dark terminals for debug?
