### ISSUE TITLE
Upgrade humantime to 2.0.0 to remove unsafe

### ISSUE THREAD

**Issue by tailhook** [sebasmagri/env_logger#151]
Hi! I've just released humantime 2.0.0 that removes a single usage of `unsafe` in the code: https://github.com/tailhook/humantime/pull/13. That usage was valid. But since some people specifically audit the code having `unsafe` I think it's still beneficial to give them fewer things to worry about. 

(no PR because the change is trivial)

**Comment by dingelish** [comment]
+1 support

**Comment by jplatte** [comment]
There's a PR that does this at #154.

**Comment by jplatte** [comment]
PR merged, this can be closed.
