### ISSUE TITLE
Memory leak detected by `MIRI`

### ISSUE THREAD

**Issue by lebensterben** [sebasmagri/env_logger#152]
`MIRI` reports memory leak when I invoke `env_logger::builder().format()` method, which takes a closure as its parameter.

A minimal example to reproduce this error is uploaded to [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d89cbd63df6dc53a2bb6d8f836fa5f09). You can click `TOOLS` and then `MIRI` to see the error.

Please let me know if this is indeed related to memory leak. And if it is, is this leak expected and I can safely ignore. Thanks

**Comment by KodrAus** [comment]
Hi @lebensterben! :wave:

I think the culprit here is the `.init` call, that sets the global logger. The `log` crate will intentionally leak a logger behind a static variable so that it's globally accessible so I think you can safely ignore that one.

**Comment by lebensterben** [comment]
>Hi @lebensterben! :wave: ...

@KodrAus thx!
