### ISSUE TITLE
Output colors support?

### ISSUE THREAD

**Issue by sebasmagri** [sebasmagri/env_logger#2]
As per [`log`'s review](https://internals.rust-lang.org/t/crate-evaluation-for-2017-05-16-log/5185). Check out `pretty_env_logger`.
[Issue in `log`](https://github.com/rust-lang-nursery/log/issues/37)

**Comment by budziq** [comment]
I'd love such feature.

Unfortunately I see is no way to support color output in cross platform way without changing the architecture somewhat ([Builder::format](https://doc.rust-lang.org/log/env_logger/struct.Builder.html#method.format) having to return a String).
https://github.com/seanmonstar/pretty-env-logger shows colored output only on ANSI compliant terminals (as there you just need to add ansi control codes to the console). I've encountered this issue when working on https://github.com/azerupi/mdBook/pull/369

**Comment by KodrAus** [comment]
We should be able to support basic colour support now that the output isn't a plain string.

I'll have a play with it using `term-painter` and see where it gets us. Are there any other recommendations for terminal colouring libs?

**Comment by lnicola** [comment]
I've also seen https://github.com/BurntSushi/ripgrep/tree/master/termcolor and https://github.com/SergioBenitez/yansi.

**Comment by KodrAus** [comment]
Hmm, `termcolor` looks interesting, thanks I'll dig into it! In classic @burntsushi style it looks like it solves all of life's problems.

**Comment by KodrAus** [comment]
Hmm, so the whole `termcolor` API is pretty interesting. Looks like [`Buffer`s + `WriteColor`](https://docs.rs/termcolor/0.3.3/termcolor/struct.Buffer.html) could neatly solve this and #31 too, but means a new public dependency.

I'll spend some time spiking it out.

**Comment by lnicola** [comment]
It seems pretty lightweight, with no extra dependencies except on Windows.

**Comment by KodrAus** [comment]
Ah sorry I think half that comment stayed in my head.

If we want to support colours using `termcolor` then we'd need to change our format function from accepting a `Box<Write>` to accepting a `Box<WriteColor>` or something. In that case we're publicly exposing `termcolor`'s API and need to be careful about upgrading it. That might not actually be a problem though. Just something I want to keep in mind.

It does look like a pretty self-contained crate though, so if this works out I don't think I'd have a problem depending on it in `env_logger`.

**Comment by BurntSushi** [comment]
I'm happy to see you're considering `termcolor`, but I would be careful of making it a public dep. I've never been particularly happy with its API. In particular, I think it is somewhat cumbersome to use. I think the idea of a `WriteColor` trait and the buffering strategy for multithreaded support is probably here to stay, but I'm particularly open to changing how colors are set and such.

Unfortunately, I don't have any specific plans as of yet to improve the API, but at this stage in the game I'm somewhat pretty relaxed about doing a semver bump on it.

**Comment by KodrAus** [comment]
Thanks for your thoughts @BurntSushi! If the API is still a bit unstable then we probably should avoid exposing it publicly, since I hope we can keep the next major release of `env_logger` around as long as the next major release of `log`.

I'm pretty sold on the `Buffer` API, which we can use privately for #31. For colours I'll play with introducing a concrete structure for the format writer rather than a trait object so we've got some more control and can at least provide some private methods for the default format to use colours.

**Comment by BurntSushi** [comment]
@KodrAus Sounds good!
