### ISSUE TITLE
Check out feedback from "Adventures in logging" post

### ISSUE THREAD

**Issue by sebasmagri** [sebasmagri/env_logger#21]
https://unhandledexpression.com/2017/08/23/adventures-in-logging/

**Comment by quadrupleslap** [comment]
The main complaint in that post was that every call allocates a string, but it looks like env_logger tries to reuse buffers now (haven't actually looked closely at it though), so it looks like this has been resolved.

**Comment by KodrAus** [comment]
I'm happy to close this now too :+1:
