### ISSUE TITLE
Issues in log repo

### ISSUE THREAD

**Issue by KodrAus** [sebasmagri/env_logger#23]
Tracking a few issues for `env_logger` that are still filed in `log`.

**Comment by KodrAus** [comment]
https://github.com/rust-lang-nursery/log/issues/210

**Comment by KodrAus** [comment]
https://github.com/rust-lang-nursery/log/issues/83

**Comment by snowe2010** [comment]
https://github.com/rust-lang-nursery/log/issues/221

**Comment by apiraino** [comment]
Hi @KodrAus are these issue being taken care of or tracked somewhere?

Specifically https://github.com/rust-lang/log/issues/210 is a longstanding known pitfall, still quite confusing before figuring that out.

thanks
