### ISSUE TITLE
Reduce noise in the timestamp format

### ISSUE THREAD

**Issue by KodrAus** [sebasmagri/env_logger#34]
Was raised in #33 that the current timestamp format is pretty verbose, but could be simpler while still being useful and valid RFC3339. We should:

- Remove nanoseconds
- Replace `+00:00` with a simple `Z`

**Comment by KodrAus** [comment]
The current implementation uses `chrono`'s formatting `Item`s to avoid allocating temporary strings or needing to parse the same format each time a record is logged. It's simple because there's only 1 `Item` to deal with. If we need to reconstruct an RFC3339 format then it'll get more complex to build the format this way.

**Comment by tailhook** [comment]
> The time crate is effectively deprecated in favour of chrono so I don't think we should depend on it directly

Well, I think this is where practicality beats purity. Since `env_logger` doesn't expose chrono's structures anywhere, it's okay to depend on `time` because it's easy to opt-out at any time.

**Comment by mjkillough** [comment]
In #35 I've attempted to make the timestamp format configurable. I wasn't able to alias `+00:00` to `Z` with this approach, but I think that should be possible with some extra changes to `chrono`. (I think it's probably worth making those changes to `chrono` anyway).
