### ISSUE TITLE
Have the formatter print the string itself.

### ISSUE THREAD

**Issue by quadrupleslap** [sebasmagri/env_logger#37]
Without this it's impossible to get colored output on Windows.

**Comment by KodrAus** [comment]
Hi @quadrupleslap! Yeh, the buffering on the `master` branch won't work with crates like `term-painter`. We use a buffer specifically designed for colouring terminals cross-platform. There is already a colouring API in `env_logger` that supports Windows terminals, but we haven't made it public yet. It just needs some design work. This does mean the only way to make `env_logger` formats use colours will be to use this API.

Feel free to chime in on how you'd like it to behave!

**Comment by KodrAus** [comment]
We've now released `0.5.0` you can get coloured output on Windows with `env_logger`. There are some more details [in the docs](https://docs.rs/env_logger/0.5.1/env_logger/fmt/index.html#formatting-log-records).

**Comment by quadrupleslap** [comment]
Thanks, this is amazing!
