### ISSUE TITLE
Accept default log level

### ISSUE THREAD

**Issue by kpcyrd** [sebasmagri/env_logger#47]
I noticed this a couple of times now: I'm considering using log and env_logger for my logging, but env_logger would require that I set RUST_LOG every time I want to actually have output, or I wouldn't get anything at all. What I want to do would be something along these lines:

```rust
env_logger::init_or("something=info");
```

So, if `$RUST_LOG` is not set, env_logger would use `something=info` instead. This could be overwritten with `RUST_LOG= ./app`, causing env_logger to use an empty string.

**Comment by tailhook** [comment]
I do this in every other application. Usually I use `env::set_var`, but it looks ugly.

Mostly my use case is setting log level to `warn` or `info` (instead of `error` which is default) so I'm not sure that parsing string is most useful thing here, but it would work for me.

**Comment by KodrAus** [comment]
I think it would be good to have a nice way to default the filter without having to dig into `std::env` yourself. In #46 I've introduced an `Env` type, because we now have multiple environment variables controlling the logger (one for the filter, and one for color output). That still needs some more design work, but I think that could impact how we approach this. Maybe after that's done we should revisit this and come up with a nice way to support it that'll scale with other new features?

**Comment by KodrAus** [comment]
My thinking for this issue is that we could use the `Env` type to do something like this strawman API:

```rust
env_logger::init_from_env(Env::default().default_filter_value("info"));
```

That is, we store an optional `or_else` value alongside each environment variable that's returned if the environment variable isn't present. We can bikeshed the actual API, it would be nice to specify a default without having to specify the environment variable, and keep the methods chainable so `Env`s can be ergonomically built up and passed to `from_env` methods.

What do you think?

**Comment by tailhook** [comment]
Looks okay. I might also prefer a type-safe variant:
````````
env_logger::init_from_env(Env::default().default_level(Info));
``````````````

**Comment by kpcyrd** [comment]
Would work for me, but seems somewhat verbose compared to the nice and easy `env_logger::init();`

My usecase is specifically that I set the log level for parts of my program, so I don't clutter stdout with info! lines from a library I use internally:

```
env_logger::init_from_env(Env::default().default_filter_value("something=info"));
```

**Comment by frol** [comment]
This is not as short as `env_logger::init()`, but still short enough:

```rust
env_logger::Builder::from_default_env().parse("info").init();
```

**Comment by KodrAus** [comment]
@frol unfortunately that will clobber any value read from the environment with `info`. I've got a PR open now that should close this one off.

**Comment by mleonhard** [comment]
Thanks for implementing this feature.  Here's how I'm using it:
```rust
env_logger::init_from_env(
    env_logger::Env::default().filter_or(env_logger::DEFAULT_FILTER_ENV, "info"));
```

A complete example:
```rust
// main.rs
extern crate env_logger;
extern crate log;

pub mod mylib {
    pub fn error() { log::error!("mylib"); }

    pub fn warn() { log::warn!("mylib"); }

    pub fn info() { log::info!("mylib"); }

    pub fn debug() { log::debug!("mylib"); }

    pub fn trace() { log::trace!("mylib"); }
}

fn main() {
    // https://rust-lang-nursery.github.io/rust-cookbook/development_tools/debugging/config_log.html
    // https://github.com/sebasmagri/env_logger/releases/tag/v0.5.8
    env_logger::init_from_env(
        env_logger::Env::default().filter_or(env_logger::DEFAULT_FILTER_ENV, "info"));
    log::error!("main");
    log::warn!("main");
    log::info!("main");
    log::debug!("main");
    log::trace!("main");
    mylib::error();
    mylib::warn();
    mylib::info();
    mylib::debug();
    mylib::trace();

    // $ cargo run
    // [2020-04-01T20:25:25Z ERROR example] main
    // [2020-04-01T20:25:25Z WARN  example] main
    // [2020-04-01T20:25:25Z INFO  example] main
    // [2020-04-01T20:25:25Z ERROR example::mylib] mylib
    // [2020-04-01T20:25:25Z WARN  example::mylib] mylib
    // [2020-04-01T20:25:25Z INFO  example::mylib] mylib

    // You can change the default log level:
    // $ RUST_LOG=debug cargo run
    // [2020-04-01T20:25:39Z ERROR example] main
    // [2020-04-01T20:25:39Z WARN  example] main
    // [2020-04-01T20:25:39Z INFO  example] main
    // [2020-04-01T20:25:39Z DEBUG example] main
    // [2020-04-01T20:25:39Z ERROR example::mylib] mylib
    // [2020-04-01T20:25:39Z WARN  example::mylib] mylib
    // [2020-04-01T20:25:39Z INFO  example::mylib] mylib
    // [2020-04-01T20:25:39Z DEBUG example::mylib] mylib

    // You can set the default log level and module-specific log levels:
    // $ RUST_LOG="info,example::mylib=debug" cargo run
    // [2020-04-01T20:25:55Z ERROR example] main
    // [2020-04-01T20:25:55Z WARN  example] main
    // [2020-04-01T20:25:55Z INFO  example] main
    // [2020-04-01T20:25:55Z ERROR example::mylib] mylib
    // [2020-04-01T20:25:55Z WARN  example::mylib] mylib
    // [2020-04-01T20:25:55Z INFO  example::mylib] mylib
    // [2020-04-01T20:25:55Z DEBUG example::mylib] mylib

    // Be sure to include the default level.  Without it, only the specified
    // modules can log.
    // $ RUST_LOG="example::mylib=error" cargo run
    // [2020-04-01T20:26:11Z ERROR example::mylib] mylib
}
```

```toml
# Cargo.toml
[package]
name = "example"
version = "0.1.0"
[dependencies]
env_logger = "~0.7.1"
log = "~0.4.8"
```
