### ISSUE TITLE
Detect type of output to omit coloring in redirected output.

### ISSUE THREAD

**Issue by pravic** [sebasmagri/env_logger#56]
May be it is not so clear title, but

On Windows with default formatter, colors are enabled. When running some app with `env_logger` inside console, it outputs colored messaged. 
So it does (tries to do) when you redirect your app to a file (via `app.exe 2> app.log`) and that file becomes pretty messy (full of lines like `[m[32m INFO[m 2018-01-17T14:56:26Z`).

I think it would be worth to detect whether STDERR is a tty (console in terms of Windows) or a file.

I am not sure whether it is an issue of `env_logger` or `termcolor`, but `ripgrep`, for instance, behaves correctly. So may be it can be done here.

**Comment by KodrAus** [comment]
Hmm, I was hoping `ColorChoice::Auto` would be figuring this out for us. Do you have any idea what `ripgrep` is doing differently to detect the target on Windows?

**Comment by quadrupleslap** [comment]
I think this is the relevant snippet:
https://github.com/BurntSushi/ripgrep/blob/58bdc366ec292653124699940190432ae30a6732/src/args.rs#L702-L706

**Comment by kpcyrd** [comment]
It seems the same problem exists on linux as well, this command prints colored output:

```
RUST_LOG=debug cargo run 2>&1 | cat
```

**Comment by pravic** [comment]
@quadrupleslap thanks! 

I thought `is_color_supported` of termcolor does it, but nope.

**Comment by KodrAus** [comment]
Thanks for tracking that down @quadrupleslap! If anyone would like to submit a PR that fixes this that would be most welcome :)

**Comment by KodrAus** [comment]
Published [`0.5.2`](https://github.com/sebasmagri/env_logger/releases/tag/v0.5.2) with this change.
