### ISSUE TITLE
Add gray color[s].

### ISSUE THREAD

**Issue by quadrupleslap** [sebasmagri/env_logger#59]
Gray colors are useful for the less-than-essential details. But it looks like this uses termcolor, so maybe I should open an issue on BurntSushi/ripgrep instead?

**Comment by quadrupleslap** [comment]
It looks like exposing `set_intense` from termcolor and using intense black as dark-gray and non-intense white as light-gray works, but on my Solarized Dark config, that makes light-gray the same as white, and dark-gray the same as the background. Not sure if that's a problem with the config or with using `set_intense`.

**Comment by KodrAus** [comment]
Released as [`0.5.3`](https://github.com/sebasmagri/env_logger/releases/tag/v0.5.3)
