### ISSUE TITLE
Implement missing imps for Target

### ISSUE THREAD

**Issue by sebasmagri** [sebasmagri/env_logger#6]
`Target` is missing the following traits:

- [ ] `Clone`
- [ ] `Copy`
- [ ] `Eq`
- [ ] `PartialEq`
- [ ] `Ord`
- [ ] `PartialOrd`
- [ ] `Hash`

**Comment by KodrAus** [comment]
Do you think `Ord + PartialOrd` makes sense for `Target`? I'm not sure what a reasonable ordering would look like.

**Comment by mjkillough** [comment]
> Do you think `Ord + PartialOrd` makes sense for `Target`? I'm not sure what a reasonable ordering would look like.

Agreed. I've removed them from my PR #18.
