### ISSUE TITLE
Support and clearly document a means to change the default log level

### ISSUE THREAD

**Issue by ssokolow** [sebasmagri/env_logger#93]
I often write projects in Python where my logging level should be `warn` or even `info` if the user doesn't specify anything.

Currently, the docs are unclear whether there's a way to set a logging level, but still allow it to be overridden by `RUST_LOG`, other than by checking for the `RUST_LOG` environment variable and setting it if it's absent before calling `env_logger::init()`... a solution which, I think you'll agree, looks like an ugly hack.

**Comment by KodrAus** [comment]
Hi @ssokolow We do actually support a better way to default the log level to something else if an environment variable isn't present using the [`Env`](https://docs.rs/env_logger/0.5.11/env_logger/struct.Env.html) type. In [this example](https://github.com/sebasmagri/env_logger/blob/master/examples/default.rs#L25-L29), we default the log level to `trace` if the variable isn't present.

You're right we don't do a great job of surfacing this, the docs could definitely be improved.
